apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: storage
resources:
- ../../base
- secret.yaml

namePrefix: prod-

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/envFrom/0/secretRef/name
      value: prod-redis-commander
  target:
    kind: Deployment
    name: redis-commander
- patch: |-
    - op: replace
      path: /metadata/name
      value: redis-commander
  target:
    kind: SealedSecret

commonAnnotations:
  env: prod
  release: 2021.02.23
  secret-sha: 3e5be07b221d5926f01198593004e2662ea53dd118aa145a52cd4c4e4cc9e140
