
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
resources:
- ../../base
- secret.yaml
- service.yaml
- ingress.yaml
- tls.yaml

namePrefix: prod-

images:
- name: mongoclient
  newName: mongoclient/mongoclient
  newTag: 4.0.0

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/envFrom/0/secretRef/name
      value: prod-mongoclient
  target:
    kind: Deployment
- patch: |-
    - op: replace
      path: /metadata/name
      value: tls-secret-mongoclient
  target:
    kind: SealedSecret
    name: prod-tls-secret-mongoclient
- patch: |-
    - op: replace
      path: /metadata/name
      value: mongoclient
  target:
    kind: SealedSecret
    name: prod-mongoclient   