apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: storage
resources:
- ../../base
- ingress.yaml
- tls.yaml

namePrefix: prod-

images:
- name: pgweb
  newName: sosedoff/pgweb
  newTag: latest

patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: tls-secret-pgweb
  target:
    kind: SealedSecret
    name: prod-tls-secret-pgweb 