apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgweb
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: pgweb
  template:
    metadata:
      labels:
        app: pgweb
    spec:
      containers:
        - name: pgweb
          image: sosedoff/pgweb:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - pgweb --listen 80 -s --bind=0.0.0.0          
          ports:
            - containerPort: 80
              name: http
              protocol: TCP